<?php

/**
 * Implementation of hook_menu().
 */
function bsdapi_example_menu() {
  $items = array();

  
  $items['bsdapi_examples'] = array(
    'title' => 'Blue State Digital API examples',
    'page callback' => 'bsdapi_examples',
    
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  
  $items['bsdapi_examples/get_constituents_by_id'] = array(
    'title' => 'Blue State Digital API examples',
    'page callback' => 'bsdapi_examples_get_constituents_by_id',
    
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  
  $items['bsdapi_examples/get_constituents'] = array(
    'title' => 'Blue State Digital API examples',
    'page callback' => 'bsdapi_examples_get_constituents',
    
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  
  return $items;
}

function bsdapi_examples(){
  $links = array();


  // Three ways to do our animal picking wizard.
  $links[] = l('get_constituents_by_id', 'bsdapi_examples/get_constituents_by_id');
  $links[] = l('get_constituents', 'bsdapi_examples/get_constituents');


  $output = theme('item_list', $links, t('Actions'));
  
  return $output;
}

function bsdapi_examples_get_constituents_by_id(){
  module_load_include('inc', 'bsdapi', 'bsdapi.class');

  $obj = new BsdApi();
  $obj -> request('cons/get_constituents_by_id', array('cons_ids'=> '1'));
  
  return 'done';
}

function bsdapi_examples_get_constituents(){
  module_load_include('inc', 'bsdapi', 'bsdapi.class');

  $obj = new BsdApi();
  $obj -> request('cons/get_constituents', array('filter' => 'state_cd=(NY,MA,IA,NV,NH,SC)'));
  
  return 'done';
}