<?php


/**
 * Implementation of hook_menu().
 */
function bsdapi_menu() {
  $items = array();
  $items['admin/settings/bsdapi'] = array(
    'title' => 'Blue State Digital API',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bsdapi_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'bsdapi.admin.inc',
  );
  
  $items['bsd'] = array(
    'title' => 'Blue State Digital API',
    'page callback' => 'bsdapi_call',
    
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  return $items;
}

function bsdapi_call(){
  //dpm($_REQUEST);
  module_load_include('inc', 'bsdapi', 'bsdapi.class');

  $obj = new BsdApi();
  return $obj -> request('cons/get_constituents_by_id', array('cons_ids'=> '1'));

}